[package]
name = "dima-cli"
version = "2.0.0-alpha.3"
authors = ["Shan Tharanga <stwm2@student.london.ac.uk>"]

[lib]
crate-type = ["cdylib"]
name = "dima"

[dependencies]
rand = "0.8.4"
linreg = "0.2.0"
maplit = "1.0.2"
reduce = "0.1.4"
bio = "0.37.0"
serde_json = "1.0.66"
serde = { version = "1.0", features = ["derive"] }
pyo3 = { version = "0.14.1", features = ["extension-module"] }

[package.metadata.maturin]
name = "dima.helpers.dima"
