name: Publish Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependancies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -q build
            python -m build
            python -m pip install sphinx_rtd_theme
      - name: Build Documentation
        run:  sphinx-build ./doc/source ./doc/html
      - name: Push Documentation to Docs Branch
        run:  |
          cd doc/html
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -B doc
          git add .
          git commit -m "Documentation Updated"
          git push