name: Publish Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install mkdocs
        run:  python -m pip install mkdocs
      - name: Deploy Documentation
        run:  mkdocs gh-deploy --config-file doc/mkdocs.yml