name: Publish Documentation

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependancies
        run:  |
          python -m pip install mkdocs
          python -m pip install mkdocs-material
      - name: Deploy Documentation
        run:  mkdocs gh-deploy --config-file doc/mkdocs.yml